version: "3.8"
services: 
    mongodb:
        image: mongo:4.4.1
        container_name: iot-mongo
        volumes: 
            - ${HOME}/databases/mongodb:/data/db
        ports: 
            - 27017:27017
        restart: unless-stopped
